# Generated by Django 6.0.4 on 2026-04-23 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('fatal', 'Fatal')], default='medium', max_length=20)),
                ('weather_condition', models.CharField(choices=[('clear', 'Clear'), ('rain', 'Rain'), ('fog', 'Fog'), ('storm', 'Storm')], default='clear', max_length=20)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('urban', 'Urban'), ('rural', 'Rural'), ('intersection', 'Intersection')], default='urban', max_length=20)),
                ('time_of_day', models.IntegerField(default=12)),
                ('day_of_week', models.IntegerField(default=1)),
                ('casualties', models.IntegerField(default=0)),
                ('fatalities', models.IntegerField(default=0)),
                ('vehicles_involved', models.IntegerField(default=1)),
                ('speed_limit', models.IntegerField(default=60)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('coverage_radius_km', models.FloatField(default=5.0)),
                ('avg_response_time_min', models.FloatField(default=10.0)),
                ('distance_score', models.FloatField(blank=True, null=True)),
                ('is_optimal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cluster_id'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('DEC', 'Deep Embedded Clustering'), ('KMeans', 'K-Means'), ('GMM', 'Gaussian Mixture Model'), ('Agglomerative', 'Agglomerative Clustering')], max_length=30)),
                ('n_clusters', models.IntegerField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('davies_bouldin_score', models.FloatField(blank=True, null=True)),
                ('calinski_harabasz_score', models.FloatField(blank=True, null=True)),
                ('distance_score', models.FloatField(blank=True, null=True)),
                ('training_time_sec', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('dispatch_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('response_time_min', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='core.accidentrecord')),
                ('ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='core.ambulancelocation')),
            ],
            options={
                'ordering': ['-dispatch_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_accident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accidentrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
